### PR TITLE
Add Transitland

### PR DESCRIPTION
**Pull request by kellytdunn**

### CODE REVIEW

**Review by d-wasserman — CHANGES_REQUESTED** [review]
Can you shorten the description to maybe the first sentence? 

Is the Provider still Mapzen? I thought it was interline now? 
https://www.interline.io/

**Comment by kellytdunn** [comment]
Sure, will do. I was going based off of the copyright info at the bottom of the page, but maybe that's different?

**Comment by kellytdunn** [comment]
Let me know if that went through ok! I see it on my end but haven't done an edit of a PR before.

**Review by d-wasserman — APPROVED** [review]
Thanks!

**Comment by d-wasserman** [comment]
Thinking on where this is, we might want to put it into public data resources rather than data specifications. I can handle this at a later date.

**Pull request merged**
